version: '3.1'

services:
  # Postgres database.
  postgres:
    image: postgres:9.6.5
    # image: timms/postgres-logging:9.6
    restart: always
    command: postgres -c 'max_connections=1' -c 'superuser_reserved_connections=0'
    environment:
      POSTGRES_USER: postgres # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres # define database
    ports:
      - 5433:5432 # Postgres port
  # Postgres database.
  pgbouncer:
    image: brainsam/pgbouncer:1.7.2
    environment:
      DB_HOST: postgres
      DB_USER: postgres # define credentials
      DB_PASSWORD: postgres # define credentials
      DB_port: 5433 # define database
      POOL_MODE: 'transaction'
      MAX_CLIENT_CONN: '2'
      # SERVER_RESET_QUERY_ALWAYS: '0'
      # SERVER_RESET_QUERY: 'DISCARD ALL'
      # SERVER_RESET_QUERY_ALWAYS: '1'
      # SERVER_RESET_QUERY: 'DEALLOCATE ALL'
    links:
      - postgres:postgres
    ports:
      - 6433:6432 # PgBouncer port
